apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: environments.devopsconsole.openshift.io
spec:
  group: devopsconsole.openshift.io
  names:
    kind: Environment
    listKind: EnvironmentList
    plural: environments
    singular: environment
    shortNames:
      - env
  scope: Namespaced
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            type:
              type: string
              enum:
                - 'deploy'
            namespace:
              type: string
            clusterRef:
              type: object
              properties:
                kind:
                  type: string
                name:
                  type: string
                apiGroup:
                  type: string
  version: v1alpha1