apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: envdeployments.devopsconsole.openshift.io
spec:
  group: devopsconsole.openshift.io
  names:
    kind: EnvDeployment
    listKind: EnvDeploymentList
    plural: envdeployments
    singular: envdeployment
    shortNames:
      - envdeploy
  scope: Namespaced
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            environmentRef:
              type: object
              properties:
                kind:
                  type: string
                name:
                  type: string
                apiGroup:
                  type: string
            deploymentRef:
              type: object
              properties:
                kind:
                  type: string
                name:
                  type: string
                apiGroup:
                  type: string
  version: v1alpha1